name: Helm Github Action
description: Setup Helm and plugins, update repositories and applies configuration
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  helm-version:
    default: 3.5.0
    description: Helm version
    required: false
  helm-command:
    default: ''
    description: Helm command arguments
    required: false
  repository-config:
    default: repositories.yaml
    description: Path to the file containing Helm repository names and URLs
    required: false
  helmfile-version:
    default: 0.138.4
    description: Helmfile version
    required: false
  helmfile-command:
    default: ''
    description: Helmfile command arguments
    required: false
  helmfile-config:
    default: helmfile.yaml
    description: Load config from file or directory.
    required: false
  environment:
    default: ''
    required: false
    description: Specify the environment name
  kube-context:
    default: ''
    required: false
    description: Set kubectl context. Uses current context by default
  log-level:
    default: info
    required: false
    description: Set log level
  plugins:
    default: secrets,diff
    required: false
    description: Helm plugins to install
outputs: {}
runs:
  using: docker
  image: Dockerfile
